# -*- coding: utf-8 -*-

from PyQt4 import QtCore, QtGui
import numpy as np
import pyqtgraph as pg
from pyqtgraph import GraphicsLayoutWidget
import sounddevice as sd

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class MainWindow(QtGui.QMainWindow):

    def __init__(self, parent=None):
        super(MainWindow, self).__init__(parent)
        self.setupUi()

    def setupUi(self):
        self.setObjectName(_fromUtf8("MainWindow"))
        self.resize(900, 675)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMinimumSize(QtCore.QSize(900, 675))
        self.setMaximumSize(QtCore.QSize(900, 675))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        self.setFont(font)
        self.centralwidget = QtGui.QWidget(self)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 901, 671))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setMargin(10)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.info_layout = QtGui.QVBoxLayout()
        self.info_layout.setContentsMargins(11, 10, 10, 10)
        self.info_layout.setSpacing(5)
        self.info_layout.setObjectName(_fromUtf8("info_layout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_settings = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_settings.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_settings.setFrameShape(QtGui.QFrame.Box)
        self.label_settings.setObjectName(_fromUtf8("label_settings"))
        self.verticalLayout.addWidget(self.label_settings)
        self.label_select_mode = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_select_mode.setObjectName(_fromUtf8("label_select_mode"))
        self.verticalLayout.addWidget(self.label_select_mode)
        self.radioButton_2 = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_2.setToolTip(_fromUtf8("Mode: DMTF encoder (play tones)"))
        self.radioButton_2.setShortcut(_fromUtf8(""))
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton.setToolTip(_fromUtf8("Mode: DMTF decoder (record tones)"))
        self.radioButton.setStatusTip(_fromUtf8(""))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.verticalLayout.addWidget(self.radioButton)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_2 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout.addWidget(self.pushButton_2)
        self.lineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout.addWidget(self.lineEdit)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.input_save_audio = QtGui.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_save_audio.sizePolicy().hasHeightForWidth())
        self.input_save_audio.setSizePolicy(sizePolicy)
        self.input_save_audio.setInputMask(_fromUtf8(""))
        self.input_save_audio.setText(_fromUtf8(""))
        self.input_save_audio.setMaxLength(32763)
        self.input_save_audio.setObjectName(_fromUtf8("input_save_audio"))
        self.verticalLayout.addWidget(self.input_save_audio)
        self.pushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label_save_charts = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_save_charts.setObjectName(_fromUtf8("label_save_charts"))
        self.verticalLayout.addWidget(self.label_save_charts)
        self.input_save_graph1 = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.input_save_graph1.setText(_fromUtf8(""))
        self.input_save_graph1.setObjectName(_fromUtf8("input_save_graph1"))
        self.verticalLayout.addWidget(self.input_save_graph1)
        self.input_save_graph2 = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.input_save_graph2.setText(_fromUtf8(""))
        self.input_save_graph2.setObjectName(_fromUtf8("input_save_graph2"))
        self.verticalLayout.addWidget(self.input_save_graph2)
        self.pushButton_3 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout.addWidget(self.pushButton_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.dtmf_label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.dtmf_label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.dtmf_label.setFrameShape(QtGui.QFrame.Box)
        self.dtmf_label.setObjectName(_fromUtf8("dtmf_label"))
        self.verticalLayout_2.addWidget(self.dtmf_label)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.dtmf_button_4 = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_4.sizePolicy().hasHeightForWidth())
        self.dtmf_button_4.setSizePolicy(sizePolicy)
        self.dtmf_button_4.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_4.setObjectName(_fromUtf8("dtmf_button_4"))
        self.gridLayout_2.addWidget(self.dtmf_button_4, 1, 1, 1, 1)
        self.dtmf_button_3 = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_3.sizePolicy().hasHeightForWidth())
        self.dtmf_button_3.setSizePolicy(sizePolicy)
        self.dtmf_button_3.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_3.setObjectName(_fromUtf8("dtmf_button_3"))
        self.gridLayout_2.addWidget(self.dtmf_button_3, 0, 3, 1, 1)
        self.dtmf_button_0 = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_0.sizePolicy().hasHeightForWidth())
        self.dtmf_button_0.setSizePolicy(sizePolicy)
        self.dtmf_button_0.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_0.setObjectName(_fromUtf8("dtmf_button_0"))
        self.gridLayout_2.addWidget(self.dtmf_button_0, 3, 2, 1, 1)
        self.dtmf_button_9 = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_9.sizePolicy().hasHeightForWidth())
        self.dtmf_button_9.setSizePolicy(sizePolicy)
        self.dtmf_button_9.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_9.setObjectName(_fromUtf8("dtmf_button_9"))
        self.gridLayout_2.addWidget(self.dtmf_button_9, 2, 3, 1, 1)
        self.dtmf_button_2 = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_2.sizePolicy().hasHeightForWidth())
        self.dtmf_button_2.setSizePolicy(sizePolicy)
        self.dtmf_button_2.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_2.setObjectName(_fromUtf8("dtmf_button_2"))
        self.gridLayout_2.addWidget(self.dtmf_button_2, 0, 2, 1, 1)
        self.dtmf_button_7 = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_7.sizePolicy().hasHeightForWidth())
        self.dtmf_button_7.setSizePolicy(sizePolicy)
        self.dtmf_button_7.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_7.setObjectName(_fromUtf8("dtmf_button_7"))
        self.gridLayout_2.addWidget(self.dtmf_button_7, 2, 1, 1, 1)
        self.dtmf_button_8 = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_8.sizePolicy().hasHeightForWidth())
        self.dtmf_button_8.setSizePolicy(sizePolicy)
        self.dtmf_button_8.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_8.setObjectName(_fromUtf8("dtmf_button_8"))
        self.gridLayout_2.addWidget(self.dtmf_button_8, 2, 2, 1, 1)
        self.dtmf_button_5 = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_5.sizePolicy().hasHeightForWidth())
        self.dtmf_button_5.setSizePolicy(sizePolicy)
        self.dtmf_button_5.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_5.setObjectName(_fromUtf8("dtmf_button_5"))
        self.gridLayout_2.addWidget(self.dtmf_button_5, 1, 2, 1, 1)
        self.dtmf_button_1 = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_1.sizePolicy().hasHeightForWidth())
        self.dtmf_button_1.setSizePolicy(sizePolicy)
        self.dtmf_button_1.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_1.setObjectName(_fromUtf8("dtmf_button_1"))
        self.gridLayout_2.addWidget(self.dtmf_button_1, 0, 1, 1, 1)
        self.dtmf_button_ast = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_ast.sizePolicy().hasHeightForWidth())
        self.dtmf_button_ast.setSizePolicy(sizePolicy)
        self.dtmf_button_ast.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_ast.setObjectName(_fromUtf8("dtmf_button_ast"))
        self.gridLayout_2.addWidget(self.dtmf_button_ast, 3, 1, 1, 1)
        self.dtmf_button_6 = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_6.sizePolicy().hasHeightForWidth())
        self.dtmf_button_6.setSizePolicy(sizePolicy)
        self.dtmf_button_6.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_6.setObjectName(_fromUtf8("dtmf_button_6"))
        self.gridLayout_2.addWidget(self.dtmf_button_6, 1, 3, 1, 1)
        self.dtmf_button_hash = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_hash.sizePolicy().hasHeightForWidth())
        self.dtmf_button_hash.setSizePolicy(sizePolicy)
        self.dtmf_button_hash.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_hash.setObjectName(_fromUtf8("dtmf_button_hash"))
        self.gridLayout_2.addWidget(self.dtmf_button_hash, 3, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.info_layout.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.info_layout.addItem(spacerItem3)
        self.console_label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.console_label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.console_label.setFrameShape(QtGui.QFrame.Box)
        self.console_label.setObjectName(_fromUtf8("console_label"))
        self.info_layout.addWidget(self.console_label)
        self.console_display = QtGui.QListWidget(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.console_display.sizePolicy().hasHeightForWidth())
        self.console_display.setSizePolicy(sizePolicy)
        self.console_display.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
                                                    "font: 8pt \"Consolas\";\n"
                                                    "color: rgb(0, 255, 0);"))
        self.console_display.setObjectName(_fromUtf8("console_display"))
        self.info_layout.addWidget(self.console_display)
        self.horizontalLayout.addLayout(self.info_layout)
        self.plot_layout = QtGui.QVBoxLayout()
        self.plot_layout.setMargin(10)
        self.plot_layout.setSpacing(5)
        self.plot_layout.setObjectName(_fromUtf8("plot_layout"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label.setFrameShape(QtGui.QFrame.Box)
        self.label.setObjectName(_fromUtf8("label"))
        self.plot_layout.addWidget(self.label)
        self.graphicsView = GraphicsLayoutWidget(self.horizontalLayoutWidget)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.plot_layout.addWidget(self.graphicsView)
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_5.setFrameShape(QtGui.QFrame.Box)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.plot_layout.addWidget(self.label_5)
        self.graphicsView_2 = GraphicsLayoutWidget(self.horizontalLayoutWidget)
        self.graphicsView_2.setObjectName(_fromUtf8("graphicsView_2"))
        self.plot_layout.addWidget(self.graphicsView_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_10 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.horizontalLayout_3.addWidget(self.pushButton_10)
        self.pushButton_11 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.horizontalLayout_3.addWidget(self.pushButton_11)
        self.plot_layout.addLayout(self.horizontalLayout_3)
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.plot_layout.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.plot_layout)
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

        #DTMF Buttons Connections
        self.dtmf_button_0.clicked.connect(lambda: self.makeTone(0))
        self.dtmf_button_1.clicked.connect(lambda: self.makeTone(1)) 
        self.dtmf_button_2.clicked.connect(lambda: self.makeTone(2)) 
        self.dtmf_button_3.clicked.connect(lambda: self.makeTone(3)) 
        self.dtmf_button_4.clicked.connect(lambda: self.makeTone(4)) 
        self.dtmf_button_5.clicked.connect(lambda: self.makeTone(5)) 
        self.dtmf_button_6.clicked.connect(lambda: self.makeTone(6)) 
        self.dtmf_button_7.clicked.connect(lambda: self.makeTone(7)) 
        self.dtmf_button_8.clicked.connect(lambda: self.makeTone(8)) 
        self.dtmf_button_9.clicked.connect(lambda: self.makeTone(9)) 
        self.dtmf_button_ast.clicked.connect(lambda: self.makeTone("*")) 
        self.dtmf_button_hash.clicked.connect(lambda: self.makeTone("#")) 

    def retranslateUi(self):
        self.setWindowTitle(_translate("MainWindow", "MPMF", None))
        self.label_settings.setText(_translate("MainWindow", "Settings", None))
        self.label_select_mode.setText(_translate("MainWindow", "Select Mode", None))
        self.radioButton_2.setText(_translate("MainWindow", "Encoder", None))
        self.radioButton.setText(_translate("MainWindow", "Decoder", None))
        self.pushButton_2.setText(_translate("MainWindow", "Load audio file", None))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "audio_file.wav", None))
        self.input_save_audio.setPlaceholderText(_translate("MainWindow", "audio_file.wav", None))
        self.pushButton.setText(_translate("MainWindow", "Save", None))
        self.label_save_charts.setText(_translate("MainWindow", "Save charts", None))
        self.input_save_graph1.setPlaceholderText(_translate("MainWindow", "graph_audio.png", None))
        self.input_save_graph2.setPlaceholderText(_translate("MainWindow", "fourier_audio.png", None))
        self.pushButton_3.setText(_translate("MainWindow", "Save", None))
        self.dtmf_label.setText(_translate("MainWindow", "DTMF", None))
        self.dtmf_button_4.setText(_translate("MainWindow", "4", None))
        self.dtmf_button_3.setText(_translate("MainWindow", "3", None))
        self.dtmf_button_0.setText(_translate("MainWindow", "0", None))
        self.dtmf_button_9.setText(_translate("MainWindow", "9", None))
        self.dtmf_button_2.setText(_translate("MainWindow", "2", None))
        self.dtmf_button_7.setText(_translate("MainWindow", "7", None))
        self.dtmf_button_8.setText(_translate("MainWindow", "8", None))
        self.dtmf_button_5.setText(_translate("MainWindow", "5", None))
        self.dtmf_button_1.setText(_translate("MainWindow", "1", None))
        self.dtmf_button_ast.setText(_translate("MainWindow", "*", None))
        self.dtmf_button_6.setText(_translate("MainWindow", "6", None))
        self.dtmf_button_hash.setText(_translate("MainWindow", "#", None))
        self.console_label.setText(_translate("MainWindow", "Console", None))
        self.label.setToolTip(_translate("MainWindow", "Real time data from the source (mic or audio file)", None))
        self.label.setText(_translate("MainWindow", "Real Time Plot", None))
        self.label_5.setToolTip(_translate("MainWindow", "Fourier transform from data source above", None))
        self.label_5.setText(_translate("MainWindow", "Real Time Plot - Fourier", None))
        self.pushButton_10.setText(_translate("MainWindow", "Record Mic", None))
        self.pushButton_11.setText(_translate("MainWindow", "Stop Mic Recording", None))
        self.label_6.setText(_translate("MainWindow", "Recording Device: ", None))

    def getTone(self, tone):
        DTMF = {1: (697, 1209),
                2: (697, 1336),
                3: (697, 1477),
                4: (770, 1209),
                5: (770, 1336),
                6: (770, 1477),
                7: (852, 1209),
                8: (852, 1336),
                9: (852, 1477),
                "*": (941, 1209),
                0: (941, 1336),
                "#": (941, 1477),
                } 
        return DTMF.get(tone)

    def makeTone(self, tone):
        self.fs = 44100
        Tone = self.createToneWave(self.getTone(tone))
        sd.play(Tone, self.fs)

        tom_reproduzido = "Tom {0} reproduzido".format(tone)
        self.console(tom_reproduzido)

    def createToneWave(self, tone):
        self.periodo = 1
        self.duration = 5
        self.fs = 44100
        
        x = np.linspace(0, self.periodo, self.fs * self.periodo)
        lower, higher = tone
        return np.sin(2 * np.pi * x * lower) + np.sin(2 * np.pi * x * higher)

    def console(self, text):
        self.console_display.addItem(text)

if __name__ == '__main__':
    app = QtGui.QApplication([])
    window = MainWindow()
    window.show()
    app.exec_() 
